import clsx from "clsx";
import type { Metadata } from "next";
import { Caveat, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const caveat = Caveat({ subsets: ["latin"], variable: "--font-caveat" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(inter.variable, caveat.variable)}>
      <body>
        <div className="flex w-full justify-center font-inter">
          <div className="w-full max-w-5xl">{children}</div>
        </div>
      </body>
    </html>
  );
}
